[program:downloads-api]
command=/usr/bin/python3 /etc/neko/supervisord/downloads-api.py
environment=DOWNLOADS_DIR="/home/neko/Downloads",PORT="9231"
autostart=true
autorestart=true
startsecs=2
startretries=5
stdout_logfile=/var/log/neko/downloads-api.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=2
stderr_logfile=/var/log/neko/downloads-api.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=2
